#
#  @(#) $Id: Makefile.config,v 1.2 2006/06/11 11:14:24 roi Exp $
# 

#
#  Makefile のシステム依存部分（LPC23XX用）
#

#
#  コンパイルフラグ
#
INCLUDES := $(INCLUDES) -I$(SRCDIR)/config/$(CPU)/$(SYS)
COPTS    := $(COPTS) -mcpu=arm7tdmi -Wa,--gstabs -mthumb -mthumb-interwork 
LDFLAGS  := $(LDFLAGS) -mcpu=arm7tdmi -mthumb -mthumb-interwork -N 

#
# カーネルに関する定義
#
KERNEL_DIR     := $(KERNEL_DIR):$(SRCDIR)/config/$(CPU)/$(SYS)
KERNEL_ASMOBJS := $(KERNEL_ASMOBJS) sys_support.o
KERNEL_COBJS   := $(KERNEL_COBJS) sys_config.o lpc2300.o

#
#  リンカスクリプトの定義
#
LDSCRIPT = $(CPU)/$(SYS)/lpc2300.ld


#
#  ターゲットボード依存の定義
#

#  INTEGRATOR用
COPTS   := $(COPTS) -D__LPC2300__ -mlittle-endian
LDFLAGS := $(LDFLAGS) -mlittle-endian 

