#
#	Makefile のターゲットシステム依存部（EZ-KIT Lite BF527用）
#

#
#  コンパイルオプション
#
INCLUDES := $(INCLUDES) -I$(CONFIGDIR)/$(CPU)/$(SYS)  -I$(CONFIGDIR)/$(CPU)/_common_bf527 \
			-I$(SRCDIR)/pdic/simple_sio
COPTS := $(COPTS)
LDFLAGS := $(LDFLAGS)

#
#  カーネルに関する定義
#
KERNEL_DIR := $(KERNEL_DIR):$(CONFIGDIR)/$(CPU)/$(SYS):$(CONFIGDIR)/$(CPU)/_common_bf527 \
				:$(SRCDIR)/pdic/simple_sio
KERNEL_ASMOBJS := $(KERNEL_ASMOBJS)
KERNEL_COBJS := $(KERNEL_COBJS) chip_config.o uart.o chip_debugboot.o

#
#  リンカスクリプトの定義
#
LDSCRIPT = $(CPU)/_common_bf527/bf527elf.ld

