/* This file is generated by genoffset. */

#define TCB_p_tinib	8
#define TCB_texptn	16
#define TCB_sp	24
#define TCB_pc	28
#define TINIB_exinf	4
#define TINIB_task	8
#define PCB_p_runtsk	16
#define PCB_p_schedtsk	20
#define PCB_reqflg	24
#define PCB_disdsp	88
#define PCB_dspflg	28
#define PCB_locspnid	32
#define PCB_p_firstlock	8
#define PCB_p_secondlock	12
#define PCB_excpt_nest_count	68
#define PCB_istkpt	72
#define PCB_p_exch_table	76
#define PCB_idf	44
#define PCB_ipm	48
#define PCB_p_ipm_mask_table	56
#define PCB_p_inh_table	60
#define PCB_p_inh_ipm_table	64
#define TCB_enatex	14
#define TCB_enatex_bit	2
#define TCB_enatex_mask	0x4
