#
#  Makefile のシステム依存部分（MIPS4KE, Malta用）
#

#
#  ターゲットアーキテクチャの定義
#
TARGET = mipsel-nec-elf

#
#  コンパイルオプション
#
INCLUDES := $(INCLUDES) -I$(CONFIGDIR)/$(CPU)/$(SYS)
COPTS := $(COPTS) -mips32 -EL -g -G0 -O2
LDFLAGS := $(LDFLAGS)
ifndef STATUS_BEV
	STATUS_BEV = 0
endif
CDEFS := $(CDEFS) -DSTATUS_BEV=$(STATUS_BEV)

#
#  カーネルに関する定義
#
KERNEL_DIR := $(KERNEL_DIR):$(CONFIGDIR)/$(CPU)/$(SYS)
KERNEL_ASMOBJS := $(KERNEL_ASMOBJS) sys_support.o
KERNEL_COBJS := $(KERNEL_COBJS) sys_config.o cbus_uart.o
# cbus_uart.o は、ボード搭載シリアルコントローラ関係のオブジェクトファイル

#
#  リンカスクリプトの定義
#
LDSCRIPT = $(CPU)/$(SYS)/malta_elf_bev$(STATUS_BEV).ld

